### ISSUE TITLE
may be the repo forgot submit some files

### ISSUE THREAD

**Issue by youjibiying** [twistedcubic/HNHN#1]
import model.model as hgcn_model
import config.config as hgcn_config
import train as hgnn_train

Traceback (most recent call last):
  File "E:/pythonCode/HNHN/baseline.py", line 18, in <module>
    import model.model as hgcn_model
ModuleNotFoundError: No module named 'model'

**Comment by twistedcubic** [comment]
Hi @youjibiying, 

These are the external baseline models we compared with, in `baselines.py`, both HGCN and HGNN. They can be found in their respective GitHub repositories as indicated in their respective papers. 

These baselines directories are set up as `hypergcn` and `hgnn`, as indicated in the [`init` script](https://github.com/twistedcubic/HNHN/blob/master/_init_paths.py#L16).

Note that these are optional, to run HNHN these models are not required.
